### ISSUE TITLE
Site Error

### ISSUE THREAD

**Issue by Brax-Tech** [wheresfrank/voterr#4]
Well going through attempting to find a movie got error that is attached in a photos. Session is still open however when trying to go back in getting the same error. 376 total votes. 
![IMG_4502](https://github.com/user-attachments/assets/9267bf9f-9787-48ac-9757-e3aaf54e2e57)

**Comment by wheresfrank** [comment]
@Brax-Tech Can you see if you're still getting the error and if you are, send over a link to the voting session so I can get the session id

**Comment by Brax-Tech** [comment]
No longer getting error. Picked a few more movies and that did work.
https://voterr.tv/join?token=4370dbe5e9e82aa974b9

**Comment by wheresfrank** [comment]
Awesome! I pushed a change today to add a placeholder for posters in case the API didn't pull in a result. The nil poster URL value could have been causing it. I'll be closing this issue for now. Let me know if it pops back up.
